### ISSUE TITLE
How to deal with new entities

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#2]
_This issue is not so much about the schema itself but related to the integration of the view in Home Assistant._

Problem: when new entities are added to Home Assistant, the user wants to see them on a view.

Solution:
Whenever a new entity is added to the entity registry, we will dynamically place it on a view.

This algorithm should work good enough so that during onboarding, when a user is going to configure a lot of devices, the resulting frontend should not look weird.

**Comment by andrey-git** [comment]
So the BE is going to edit the `ui.yaml` to add the new entity? To which view?

**Comment by balloob** [comment]
By default we can do the first (?) view and make it user configurable.

**Comment by SteveMacLowell** [comment]
What about a hidden 'All' view that is accessible from a menu of some sort? As the name implies, all entities would be added to this view and can be dealt with further from there.

**Comment by ciotlosm** [comment]
I'd recommend you setup a default configuration for `ui-lovelace.yaml` that includes some very smart entity-filter cards. I also recommend you have a way to have the filter only show the entities that the user hasn't defined cards for. 

The initial view based on defaults can be done (Based on what it's available like entity-filter) in a smart way that adapts easy and it's useful to new users. For example device_trackers to be in their own glance card if that would have a filter.

**Comment by peternijssen** [comment]
Hope it's okay to share some feedback as a user :)

The thing I am really missing, is an overview of entities that I did not add yet to the interface. Maybe because I didn't want to, but since I don't know which I missed, I have to walk through all entities and check if either;
A) I've added them
B) I didn't want to add them.

Perhaps you can generate some sort of view, or automatically generate it with the click on a button, which adds all entities that you didn't add to the interface yet.

This way, for everyone who has been using HA already for a while, they can get a nice overview of what they didn't add. 
For anyone who is new, they can easily generate an UI that includes the entities which HA discovered, but weren't added to the view.

Perhaps this way you solve the problem of newly added entities but also for experienced users to find out what they didn't add.

**Comment by ciotlosm** [comment]
@peternijssen majority of your needs are covered by Unused Entities option available in Lovelace (top right menu)

**Comment by Kane610** [comment]
One thing not covered here (and might not be appropriate here). But I'll mention it either way, there is no registry or list of what events you can actually listen to based on what components that are enabled on your specific system.

Might be the next step after this discussion has been completed.

**Comment by adonno** [comment]
I'm not sure if this is a Bug but i have sevreal entities in my picture-elements card and they still show-up in my unused entities list? 

https://hastebin.com/bekerimira.bash

**Comment by zsarnett** [comment]
So we now have new entities that are pushed to the `unused entities` page. Do we want to close this discussion and open a new one for discussing how we are going to handle new entities in the future with Lovelace being default UI as well as discussing new users after they set up their components, adding a view with all their components similar to how the default UI does it. With the new UI editor their is a lot to discuss

**Comment by balloob** [comment]
Yes, we should close this. I agree that we satisfy enough for MVP default Lovelace

**Comment by Morphy99** [comment]
I couldn't find if a new issue got opened relating to this or if the discussion carried on elsewhere but I have this suggestion:
New entities are added to unused entities and for me this is fine apart from we can't do anything from this apart from view them. I can't even copy the entity id to be able to add it to the main UI. The ability to move it or duplicate it from unused entities would make perfect sense if its not too hard to implement technically.

**Comment by balloob** [comment]
This issue has been resolved. Please open a new one.
