### ISSUE TITLE
Filter-card: exclude filter, attribute filter

### ISSUE THREAD

**Issue by broux2** [home-assistant/ui-schema#41]
It would be nice to filter by attributes such as “hidden”.

**Comment by c727** [comment]
`hidden` is deprecated btw

**Comment by balloob** [comment]
Yep, and if we add an attribute filter, people will fall back to using customize and hidden attributes 😢 

Instead we should just add an exclude option to entity-filter that has the exact same syntax as the filters.

**Comment by broux2** [comment]
I’m open to however it can work. 

I can’t find anything that says hidden is deprecated. It is even still a dropdown item in the customize panel.

**Comment by balloob** [comment]
It's deprecated as part of lovelace. It's still active in the old UI. The customize panel controls how entities looked in the old UI by storing that configuration in the state machine. Lovelace completely moves away from that: https://developers.home-assistant.io/docs/en/lovelace_index.html#how-it-works

**Comment by ciotlosm** [comment]
I'm thinking out loud here:
- If i have lights and switches combined because I used auto-discovery and tasmota I'd like a way to exclude actual lights from switches with entity filter even if they are discovered under the same domain, and something easier then me naming my light switches with "light" in the name
- If I have multiple domain trackers, but half are "guest" I'd like a way to differentiate those
- The sensors under binary_sensor will also serve different functions and people might want to put them in different groups

One option I can think of is json_attributes that were discussed in a different PR where you could allow totally arbitrary values to be attaches to sensors (and maybe other entities) by discovery and allow filtering based on those.

**Comment by balloob** [comment]
Rule #1 of Lovelace: we do not store UI configuration in the state machine. 

I feel like the filter card sometimes makes people lazy because they don't want to write out 15 entities. But how often do lights change? Entity IDs should not change. Should be easier to just list them all instead of creating crazy filter combinations ;)

**Comment by ciotlosm** [comment]
The alternative would be to use filter on other cards to filter existing "entities" in the list based on a "state".

`entity-filter` main advantage for adoption is the ability to adapt because of filters to changes in your entity list. I agree this is also problematic depending on the logic of the layout.

My examples above would work if filter was available for `glance` and `entities` cards. 
The disadvantage would be that if you have a card that shows you all lights or movement sensors you would have to manually add new sensors in to this card as well every time you add a sensor. Depending on the many views and groupings you have this can be tedious remembering where you usually put in motion sensors. Automatic cards have power in this case.

**Comment by c727** [comment]
I also think that the filter not be abused to group entities and people should define their entities once instead

Maybe we should remove domain and entity from filter again.

Or we remove the filter card and create a function for cards with `entities` to filter some entities based on state (or attribute) ?

**Comment by balloob** [comment]
We've slimmed down the entity filter options to just filter on states on a prepopulated group of entities. This feature request is no longer relevant.

**Comment by da-anda** [comment]
if filtering by domain is removed now, how do I need to configure lovelace to show auto-detected UPNP media players? I hope you don't suggest to add them manually after they got detected (which basically makes auto-discovery pointless)

**Comment by balloob** [comment]
Home Assistant is moving away from discovery -> entity and instead if moving to discovery -> config entry -> entity. Config entry is caching the discovery. So that would not have worked in the future anyway.

If you want it, consider a custom card. It won't be part of the built-in cards.
